development:
  access_key_id: AKIAILGXATYAF2CU6C6A
  secret_access_key: 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
  bucket: MP3Player
  # access_key_id: 0KGQP159FKZ2CHEPTVG2
  # secret_access_key: kokLMvyrpS9SJkqC8lKoVc4jw/oEHSY07utM9n/m
  # bucket: MP3Player
